### ISSUE TITLE
Cannot install addons: Python AttributeError

### ISSUE THREAD

**Issue by strawberrymetropolis** [trevorsandy/blenderldrawrender#3]
When trying to install the addons, an `AttributeError` occurs. Here is the log:

```
Blender 4.0.1 (hash d0dd92834a08 built 2023-11-17 00:36:52)
INFO: Installing LDraw Addon...
Collecting debugpy
  Downloading debugpy-1.8.2-cp310-cp310-win_amd64.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 4.9 MB/s eta 0:00:00
Installing collected packages: debugpy
Successfully installed debugpy-1.8.2
Collecting pillow
  Downloading pillow-10.4.0-cp310-cp310-win_amd64.whl (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 5.8 MB/s eta 0:00:00
Installing collected packages: pillow
Successfully installed pillow-10.4.0
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_import_ldraw\__init__.py", line 35, in <module>
    from . import importldraw
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_import_ldraw\importldraw.py", line 40, in <module>
    from .loadldraw import loadldraw
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_import_ldraw\loadldraw\loadldraw.py", line 2364, in <module>
    class BlenderMaterials:
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_import_ldraw\loadldraw\loadldraw.py", line 2368, in BlenderMaterials
    __hasPrincipledShader = "ShaderNodeBsdfPrincipled" in [node.nodetype for node in getattr(bpy.types, "NODE_MT_category_SH_NEW_SHADER").category.items(None)]
AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_SHADER'
```

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Indeed, the last released version was not compatible with Blender 4.0 and above. I will correct this issue shortly.

Cheers,

**Comment by trevorsandy** [comment]
I've added Blender 4 compatibility. If you continue to experience unexpected behaviour with version v1.5.5, please let me know.

Cheers,
